# Generated by Django 5.2.8 on 2025-12-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapeamentoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mapeamento', models.CharField(max_length=100)),
                ('tabela_origem', models.CharField(max_length=100)),
                ('banco_destino', models.CharField(max_length=100)),
                ('tabela_destino', models.CharField(max_length=100)),
                ('mapa_colunas', models.JSONField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
