# Generated by Django 5.2.8 on 2025-12-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construtor_schemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('tabela_origem', models.CharField(max_length=100)),
                ('banco_destino', models.CharField(max_length=100)),
                ('tabela_destino', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
                ('total_linhas', models.IntegerField(default=0)),
            ],
        ),
    ]
