# Generated by Django 5.2.8 on 2025-11-27 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tecnico_ad_login', models.CharField(max_length=100)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('tipo_acao', models.CharField(max_length=50)),
                ('tipo_objeto', models.CharField(max_length=50)),
                ('objeto_nome', models.CharField(max_length=200)),
                ('objeto_guid', models.CharField(blank=True, max_length=100, null=True)),
                ('dados_evento', models.JSONField(default=dict)),
                ('violou_regras', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IncidenteQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('regra_violada', models.CharField(max_length=200)),
                ('descricao_incidente', models.TextField()),
                ('responsavel_resolucao', models.CharField(choices=[('GRADUACAO', 'Gerente de Acadêmicos - Graduação'), ('POS_GRADUACAO', 'Gerente de Acadêmicos - Pós-Graduação'), ('EFETIVOS', 'Gerente de Funcionários Efetivos'), ('TERCEIRIZADOS', 'Gerente de Terceirizados'), ('COMPUTADORES', 'Gerente de Computadores e Infra'), ('AD_ADMIN', 'Gerente do Active Directory (Super Admin)')], max_length=50)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Análise'), ('APROVADO_EXCECAO', 'Aprovado (Exceção Permitida)'), ('REJEITADO_CORRIGIR', 'Rejeitado (Necessita Correção)'), ('CORRIGIDO', 'Corrigido pelo Técnico')], default='PENDENTE', max_length=20)),
                ('observacao_gerente', models.TextField(blank=True, null=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('evento_auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melhoria_continua.auditoriaad')),
                ('gerente_decisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilGerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsabilidade', models.CharField(choices=[('GRADUACAO', 'Gerente de Acadêmicos - Graduação'), ('POS_GRADUACAO', 'Gerente de Acadêmicos - Pós-Graduação'), ('EFETIVOS', 'Gerente de Funcionários Efetivos'), ('TERCEIRIZADOS', 'Gerente de Terceirizados'), ('COMPUTADORES', 'Gerente de Computadores e Infra'), ('AD_ADMIN', 'Gerente do Active Directory (Super Admin)')], max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_governanca', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
