# Generated by Django 5.2.8 on 2025-11-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises_relacionais', '0002_relatoriodqi_relatorioriscosenha'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('arquivo_csv', models.CharField(blank=True, max_length=500, null=True)),
                ('total_objetos_analisados', models.IntegerField(default=0)),
                ('total_objetos_com_falha', models.IntegerField(default=0)),
                ('media_falhas_por_objeto', models.FloatField(default=0.0)),
                ('top_ofensores', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
