# Generated by Django 5.2.8 on 2025-11-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises_relacionais', '0003_relatorioscorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriodqi',
            name='tipo_ambiente',
            field=models.CharField(default='PRODUCAO', max_length=20),
        ),
    ]
