# Generated by Django 5.2.8 on 2025-12-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade_ad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConhecimentoRH',
            fields=[
                ('samaccountname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status_rh', models.CharField(max_length=100)),
                ('departamento_correto', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo_correto', models.CharField(blank=True, max_length=255, null=True)),
                ('gerente_correto_login', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('email_correto', models.CharField(blank=True, max_length=255, null=True)),
                ('data_importacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
