# Generated by Django 5.2.8 on 2025-12-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade_ad', '0002_baseconhecimentorh'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicionarioOrganizacional',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sigla', models.CharField(max_length=50)),
                ('nome_oficial', models.CharField(max_length=255)),
                ('hierarquia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MapeamentoDepartamentoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento_rh', models.CharField(max_length=255, unique=True)),
                ('prefixo_grupo_ad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioUnificado',
            fields=[
                ('samaccountname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('email_oficial', models.CharField(max_length=255)),
                ('deve_estar_ativo', models.BooleanField(default=False)),
                ('grupos_calculados', models.JSONField(default=list)),
                ('perfis_origem', models.JSONField(default=list)),
                ('data_processamento', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
