# Generated by Django 5.2.8 on 2025-12-16 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade_ad', '0003_dicionarioorganizacional_mapeamentodepartamentogrupo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DicionarioOrganograma',
            fields=[
                ('codigo_unidade', models.CharField(help_text='Código único (ex: 112406)', max_length=50, primary_key=True, serialize=False)),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('hierarquia', models.CharField(help_text='Ex: .605.102.109.', max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoOrganograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição/Renomeação'), ('IMPORTACAO', 'Importação CSV')], max_length=20)),
                ('detalhes', models.TextField(help_text="Ex: Nome alterado de 'DHI' para 'DHIST'")),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unidade_afetada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualidade_ad.dicionarioorganograma')),
            ],
        ),
        migrations.DeleteModel(
            name='DicionarioOrganizacional',
        ),
    ]
