# Generated by Django 5.2.8 on 2025-12-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade_ad', '0004_dicionarioorganograma_historicoorganograma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentidadeConsolidada',
            fields=[
                ('samaccountname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('status_calculado', models.CharField(max_length=50)),
                ('lotacao_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('lotacao_sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_vinculo_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('ggs_sugeridas', models.TextField(blank=True, help_text='Lista de GGs calculadas baseadas na regra')),
                ('data_processamento', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VinculoRH',
            fields=[
                ('matricula', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cpf', models.CharField(db_index=True, max_length=14)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_vinculo', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('lotacao_string', models.CharField(max_length=255)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
