# Generated by Django 5.2.8 on 2025-12-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade_ad', '0005_identidadeconsolidada_vinculorh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinculorh',
            options={'verbose_name': 'Vínculo de RH', 'verbose_name_plural': 'Vínculos de RH'},
        ),
        migrations.RenameField(
            model_name='vinculorh',
            old_name='lotacao_string',
            new_name='cargo',
        ),
        migrations.RemoveField(
            model_name='vinculorh',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='vinculorh',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='vinculorh',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vinculorh',
            name='tipo_vinculo',
        ),
        migrations.AddField(
            model_name='vinculorh',
            name='departamento_string',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinculorh',
            name='gerente_login',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vinculorh',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='vinculorh',
            name='samaccountname',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinculorh',
            name='status_rh',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
